spring:
  profiles:
    active: dev-local
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${db_database}/${db_schema}?autoReconnect=true&useSSL=false
#    url: jdbc:mysql://localhost:3306/springbootwaa?autoReconnect=true&useSSL=false
    username: ${db_username}
    password: ${db_password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

server:
  port: 8080

#export waa_database=localhost:3306
#export waa_schema=springbootwaa
#source ~/.bashrc
#echo $waa_database
#echo $waa_schema
